config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'products/index'
  get 'categories/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to:'categories#index'

  resources :categories do
  	resources :products, only: [:index]
  end
  get '/cart', to: 'order_items#index'
  resources :order_items, path: '/cart/items'

  get '/cart/checkout', to: 'orders#new', as: :checkout
  patch '/cart/checkout', to: 'orders#create'
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :product_categories
	has_many :products,through: :product_categories
	has_one_attached :image
end

app/models/order.rb
class Order < ApplicationRecord
	has_many :items, class_name: 'OrderItem'
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
	belongs_to :order
 	 belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord

	validates :title,presence:true
	has_many :product_categories
	has_many :categories,through: :product_categories
	has_one_attached :image
	has_many :variants, class_name: 'ProductVariant'
end

app/models/product_category.rb
class ProductCategory < ApplicationRecord
  belongs_to :product
  belongs_to :category
end

app/models/product_variant.rb
class ProductVariant < ApplicationRecord
	 belongs_to :product
	 
end

app/models/shopping_cart.rb
class ShoppingCart

	delegate :sub_total, to: :order
	def initialize(token:)
		@token =token
	end

	def order
		@order ||= Order.find_or_create_by(token: @token, status: 'cart') do |order|
			order.sub_total = 0
		end
	end

	def items_count
		order.items.sum(:quantity)
	end

	def add_item(product_id: , quantity: 1)
		product = Product.find(product_id)
		puts "Nadir quantity #{quantity}"
		order_item = order.items.find_or_initialize_by(
			product_id: product_id
			)

		order_item.price = product.price
		order_item.quantity = quantity

		ActiveRecord::Base.transaction do
			order_item.save
			update_sub_total!
		end
	end

	def remove_item(id:)
		ActiveRecord::Base.transaction do
			order.items.destroy(id)
			update_sub_total!
		end
	end

	private

	def update_sub_total!
		order.sub_total = order.items.sum('quantity * price')
		order.save
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :current_cart
	before_action :site_search

	def current_cart
		@current_cart ||= ShoppingCart.new(token: cart_token)
	end
	helper_method :current_cart

	private

	def cart_token
		return @cart_token unless @cart_token.nil?

		session[:cart_token] ||= SecureRandom.hex{8}
		@cart_token = session[:cart_token]
	end

	def site_search
		@q = Category.ransack(params[:q])
		@search_categories = @q.result
	end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
  	@categories = Category.joins(:products).select('categories.*,count(products.id) as products_count').group('categories.id').order(:title)
  	@q = Category.ransack(params[:q])
	
  end
end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController
 def index
 	@items = current_cart.order.items
 end

  def create

  	current_cart.add_item(

  		product_id: params[:product_id],
  		quantity: params[:quantity]
  		
  		)

  		redirect_to cart_path
  end

  def destroy
  	current_cart.remove_item(id: params[:id])
  	redirect_to cart_path
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

	def new
		@order = current_cart.order
	end

	def create
		@order = current_cart.order

		if @order.update_attributes(order_params.merge(status: 'open'))
			session[:cart_token] = nil
			flash[:notice] = 'Order has been completed !!!'
			redirect_to root_path
		else
			render :new
		end
	end

	private

	def order_params
		params.require(:order).permit(:first_name, :last_name)
	end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
  	@category = Category.find(params[:category_id])
  	@products = @category.products.includes(:variants).order(:title)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/categories/index.html.erb
<%= render "partials/header" %>

<div class="navbar">

	<h3>Available Categories (<%= @categories.length %>) </h3>
		<ul class="thumbnails">
			<% @categories.each do |cat| %>
			<li class="span3">
			  <div class="thumbnail">
			  	<%= link_to category_products_path(cat) do %>
				<div class = "img"><%= image_tag(cat.image,style:'height:220px')%></div>
				<div class="caption cntr">
					<p><strong> <%= cat.title %></strong></p>
					<p> (<%= cat.products_count %> Items)</p>				
					<br class="clr">
				</div>
				<% end %>
			  </div>
			</li>
			<% end %>
		</ul>

</div>
<%= render "partials/footer" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shopper</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'bootstrap', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta charset="utf-8">
    <title>Twitter Bootstrap shopping cart</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
  
  </head>

  <body>
    <p>
      <%= link_to "Home", root_path %>
      <%= link_to pluralize(current_cart.items_count,'item'), cart_path %>
    </p>
    <hr />
    <div class="flash-message">
                 <% flash.each do |key,value| %>
                  <p><%= value %></p>
                  <% end %>
              </div>
    <%= yield %>
  </body>
</html>

app/views/order_items/index.html.erb
<%= render "partials/header" %>
<!--
<h2>Current Cart</h2>

<table>
	<thead>
		<tr>
			<td>Product</td>
			<td>Price</td>
			<td>Quantity</td>
			<td></td>
		</tr>
	</thead>
	<tbody>
		<% @items.each do |item| %>
		<tr>
			<td><%= item.product.title %></td>
			<td><%= number_to_currency item.price %></td>
			<td><%= item.quantity %></td>
			<td><%= 
			form_for item, method: :delete do |f| %>
			<%= f.submit "Remove" %>
			<%  end %>
		</td>
	</tr>
	<% end %>
</tbody>
<tfoot>
	<tr>
		<td colspan="4" align="right">
			<%= number_to_currency current_cart.sub_total %>
		</td>
	</tr>
</tfoot>
</table>
<%= link_to "Checkout", checkout_path %>

-->

<div class="well well-small">
	<h1>Current Cart <small class="pull-right">  <%= pluralize(current_cart.items_count,'item') %> </small></h1>
	<hr class="soften"/>

	<table class="table table-bordered table-condensed">
		<thead>
			<tr>
				<th>Product</th>
				<th>Description</th>
				<th>	Ref. </th>
				<th>Avail.</th>
				<th>Unit price</th>
				<th>Qty </th>
				<th>Total</th>
			</tr>
		</thead>
		<tbody>
			<% @items.each do |item| %>
			<tr>
				<td><%= image_tag(item.product.image,style:'height:200px', width: '70%')%></td>
				<td><%= item.product.title %><br><br></td>
				<td> - </td>
				<td>Yes! </td>
				<td><%= number_to_currency item.price %></td>
				<td>
					<%= item.quantity %>
				</td>
				<td>
					<%= form_for item, method: :delete do |f| %>
					<%= f.submit "Remove" %>
					<%  end %>				
				</td>
			</tr>
			<% end %>
			<tr>
				<td colspan="6" class="alignR">Total products:	</td>
				<td class="label label-primary"> <%= number_to_currency current_cart.sub_total %></td>
			</tr>
		</tbody>
	</table> 

	<%= form_tag( checkout_path, :method => :get )  do %>
		<div class="control-group">
			<div class="controls">
				<button type="submit" class="shopBtn">Click to Proceed!</button>
			</div>
		</div>
	<% end %>

</div>
	
	<br/>	
	<br/>	
	<br/>		<br/>		<br/>	<br/>	<br/>	<br/>	<br/>	<br/>	<br/>	<br/>	<br/>
	<br/>
<%= render "partials/footer" %>

app/views/orders/new.html.erb
<%= render "partials/header" %>


<div class="checkout">
<h2>Checkout </h2>
<!--
<%= form_for @order, url: checkout_path do |f| %>

	<div class="form-group">
		<%= f.label :first_name %>
		<%= f.text_field :first_name %>
	</div>

	<div class="form-group">
		<%= f.label :last_name %>
		<%= f.text_field :last_name %>
	</div>
	<%= f.submit 'Checkout' %>
<% end %>
</div>

-->

<%= form_for @order, url: checkout_path do |f| %>
<div class="control-group">
		<label class="span2 control-label" for="inputEmail">FirstName</label>
		<div class="controls">
			<%= f.text_field :first_name %>
		</div>
	</div>
	<div class="control-group">
		<label class="span2 control-label" for="inputEmail">Last Name</label>
		<div class="controls">
			<%= f.text_field :last_name %>
		</div>
	</div>
	<div class="control-group">
		<label class="span2 control-label" for="inputEmail">Country</label>
		<div class="controls">
			<input type="text" placeholder="Country">
		</div>
	</div>
	<div class="control-group">
		<label class="span2 control-label" for="inputPassword">Post Code/ Zipcode</label>
		<div class="controls">
			<input type="password" placeholder="Password">
		</div>
	</div>
	<div class="control-group">
		<div class="controls">
			<button type="submit" class="shopBtn">Click to Check out</button>
		</div>
	</div>
<% end %>
</form> 
</div>

app/views/partials/_footer.html.erb

<div class="copyright">
<div class="container">
	
	<span>Copyright &copy; 2020 Nadir Shop Mart Website</span>
</div>
</div>

app/views/partials/_header.html.erb
<div class="navbar navbar-inverse navbar-fixed-top">
	<div class="topNav">
		<div class="container">
			<div class="alignR">
				
				
				<a href="cart.html"><span class="icon-shopping-cart"></span>  <%= link_to pluralize(current_cart.items_count,'item'), cart_path %><span class="badge badge-warning"> <%= link_to number_to_currency current_cart.sub_total %></span></a>
			</div>
		</div>
	</div>
</div>

<!--
Lower Header Section 
-->
<div class="container">
<header id="header">
<div class="row">
	<div class="span4">
	<h1>
	<a class="logo" href="index.html">
		<div class = "img"><%= link_to image_tag("logo-bootstrap-shoping-cart.png"),root_path %> </div>
	</a>
	</h1>
	</div>
	
	
</div>
</header>

app/views/products/index.html.erb
<%= render "partials/header" %>




<h2> Category/<%= @category.title %>/Products</h2>

<!--
Lower Header Section 
<ol>
	<% @products.each do |product| %>
	<li>
		<%= product.title %> (<%= number_to_currency product.price %>)
		<%= form_tag order_items_path do %>
		<%= hidden_field_tag :product_id,product.id %>
		<%= number_field_tag :quantity,1 %>
		<%= submit_tag "Add to Cart" %>
		<% end %>
		<ul>
			<% product.variants.each do |variant| %>
			<li><%= variant.title %> (<%= number_to_currency variant.price %>)</li>
			<% end %>
		</ul>
	</li>
	<% end %>
</ol>
-->

<% @products.each do |product| %>
<div class="row-fluid">
	<div class="span5">
		<div id="myCarousel" class="carousel slide cntr">
			<div class="carousel-inner">
				<div class="item active">
					<%= image_tag(product.image,style:'height:220px', width: '100%')%>
				</div>

			</div>
		</div>
	</div>
	<div class="span7">
		<h3><%= product.title %> [<%= number_to_currency product.price %>]</h3>
		<hr class="soft"/>


		<%= form_tag order_items_path do %>
		<div class="control-group">
			<label class="control-label"><span><%= number_to_currency product.price %></span></label>
			<div class="controls">
				<%= hidden_field_tag :product_id,product.id %>
				<%= number_field_tag :quantity,1 %>
			</div>
		</div>

		<h4>Description</h4>
		<p><%= product.description %>
		</p>
		<div class="control-group">
			<div class="controls">
				<button type="submit" class="shopBtn">Add to Cart</button>
			</div>
		</div>
		<% end %>

	</div>
</div>
<br />
<% end %>
<%= render "partials/footer" %>